point_cloud_filter_bridge:
  ros__parameters:
    input_topic: /livox/lidar
    output_topic: /livox/lidar_filtered
    debug_topic: /point_cloud_filter/debug_cloud
    stats_topic: /point_cloud_filter/filter_stats
    debug_enabled: false
    publish_stats: true
    max_processing_hz: 20.0
    dynamic_filter:
      enable: true
      publish_stats: true
      motion_threshold: 0.1
      history_size: 8
      stability_threshold: 0.75
      max_time_diff: 0.5
      search_radius: 0.2
      min_neighbors: 10
      normal_consistency_thresh: 0.8
      density_ratio_thresh: 0.5
      downsample_ratio: 1
      max_points_per_frame: 60000
      voxel_size_base: 0.01
