# Localizer配置文件
# 由配置生成器自动生成，请勿手动修改
# 生成时间: 2025-09-27 11:37:46
# 主配置文件: /home/tianyu/codes/Mid360map/config/master_config.yaml

cloud_topic: /slam/body_cloud
dynamic_filter:
  density_ratio_thresh: 0.5
  downsample_ratio: 2
  enable: false
  history_size: 5
  max_points_per_frame: 50000
  max_time_diff: 0.5
  min_neighbors: 10
  motion_threshold: 0.1
  normal_consistency_thresh: 0.8
  publish_stats: true
  search_radius: 0.2
  stability_threshold: 0.8
  voxel_size_base: 0.01
local_frame: lidar
map_frame: map
odom_topic: /slam/lio_odom
refine_map_resolution: 0.1
refine_max_iteration: 10
refine_scan_resolution: 0.1
refine_score_thresh: 0.1
rough_map_resolution: 0.25
rough_max_iteration: 5
rough_scan_resolution: 0.25
rough_score_thresh: 0.2
update_hz: 1.0
