# FAST-LIO2配置文件
# 由配置生成器自动生成，请勿手动修改
# 生成时间: 2025-10-18 11:20:55
# 主配置文件: /home/tianyu/codes/Mid360map/config/master_config.yaml

body_frame: base_link
converge_thresh: 0.0001
cube_len: 100
det_range: 30
enable_buffer_monitoring: true
esti_il: false
gravity_align: true
ieskf_max_iter: 6
imu_init_num: 500
imu_topic: /livox/imu
lidar_cov_inv: 2000.0
lidar_cov_scale: 1.0
lidar_filter_num: 1
lidar_max_range: 30.0
lidar_min_range: 0.3
lidar_topic: /livox/lidar
map_resolution: 0.25
max_imu_buffer_size: 8000
max_lidar_buffer_size: 1000
move_thresh: 0.8
na: 0.005
nba: 0.0001
nbg: 5.0e-05
near_search_num: 8
ng: 0.005
point_filter_num: 4
print_time_cost: true
r_il:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
scan_resolution: 0.2
t_il:
- 0.011
- 0.02329
- -0.04412
world_frame: odom
