imu_topic: /livox/imu
lidar_topic: /livox/lidar
body_frame: body
world_frame: map
print_time_cost: true
lidar_filter_num: 1
lidar_min_range: 0.5
lidar_max_range: 80.0
scan_resolution: 0.15
map_resolution: 0.15
cube_len: 200
det_range: 80
move_thresh: 0.5
na: 0.005
ng: 0.005
nba: 0.0001
nbg: 5.0e-05
imu_init_num: 150
near_search_num: 10
ieskf_max_iter: 6
gravity_align: true
esti_il: false
lidar_cov_inv: 5000.0
r_il:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
t_il:
- -0.011
- -0.02329
- 0.04412
