## 主配置文件（生成器会读取本文件并下发至各组件）
# 说明：
# - 支持在参数旁添加注释（# ...）。配置生成器会忽略注释，不影响正常下发。
# - 本文件为“单一事实来源”，请勿改动键名结构；仅调整数值即可。
# - 带有 ↑/↓ 的注释表示调大/调小的效果取舍（性能/精度/鲁棒性）。

system:
  name: MID360_SLAM_System
  version: '2.0'
  description: 基于Livox MID360的实时SLAM建图系统
network:
  host:
    ip: 192.168.1.50
    interface: enp7s0
    gateway: 192.168.1.1
    netmask: 255.255.255.0
  lidar:
    ip: 192.168.1.3
    lidar_ports:
      cmd_data: 56100
      push_msg: 56200
      point_data: 56300
      imu_data: 56400
      log_data: 56500
    host_ports:
      cmd_data: 56101
      push_msg: 56201
      point_data: 56301
      imu_data: 56401
      log_data: 56501
calibration:
  lidar_to_imu:
    translation:
    - 0.011
    - 0.02329
    - -0.04412
    rotation:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  lidar_to_baselink:
    translation:
    - 0.0
    - 0.0
    - 0.0
    rotation_rpy:
    - 0.0
    - 0.0
    - 0.0
frames:
  world_frame: odom
  base_frame: base_link
  lidar_frame: livox_frame
topics:
  imu: /livox/imu          # IMU话题（回放/实机一致）
  lidar: /livox/lidar      # LiDAR话题｜回放：/livox/lidar；实机：/livox/lidar_filtered（经过滤桥）
  odometry: /slam/lio_odom
  path: /slam/lio_path
  body_cloud: /slam/body_cloud
  world_cloud: /slam/world_cloud
  loop_markers: /slam/loop_markers
  hba_map: /hba/map_points
  performance: /slam/performance_metrics
  diagnostics: /slam/diagnostics
livox_driver:
  xfer_format: 1            # 数据打包｜↑(2) 吞吐↑/兼容↓；↓(1) 兼容↑/吞吐↓
  multi_topic: 0            # 多话题输出｜↑(1) 灵活/订阅多；↓(0) 简单
  data_src: 0               # 数据源 0=设备 1=文件｜一般保持0
  publish_freq: 10.0        # 发布频率Hz｜↑ 实时↑/CPU↑；↓ 轻量/时间分辨率↓
  output_data_type: 0       # 输出类型｜↑(1/带更多域) 可视化↑/带宽↑；↓(0/XYZI) 轻量
  frame_id: livox_frame     # 传感器坐标系
  cmdline_input_bd_code: livox0000000001
  lidar_config:
    pcl_data_type: 1        # 点格式｜↑ 通道多/带宽↑；↓ 轻量
    pattern_mode: 1         # 扫描模式｜↑(1) 细节↑/带宽↑；↓(0) 速度↑/细节↓
fastlio2:
  print_time_cost: true     # 打印耗时｜↑ 便于调试；↓ 安静
  lidar_filter_num: 1       # 点云滤波次数｜↑ 速度↑/细节↓；↓ 细节↑/耗时↑（回放易稀疏→降为1保点）
  lidar_min_range: 0.3      # 最近距离m｜↑ 近噪↓/近结构↓；↓ 近细节↑/噪声↑（尾段易空→适度放宽）
  lidar_max_range: 30.0     # 最远距离m｜↑ 远距鲁棒↑/耗时↑；↓ 速度↑/远距↓（扩大以提升可用邻域）
  scan_resolution: 0.2     # 扫描分辨率m｜↑ 更粗更快；↓ 更细更慢（适度更细保留更多特征）
  map_resolution: 0.25      # 地图分辨率m｜↑ 更粗更快；↓ 更细更慢（略微更密提高邻域命中）
  cube_len: 100             # 局部地图范围m｜↑ 内存↑/稳定↑；↓ 轻量/退化风险↑
  det_range: 30             # 匹配检测范围m｜↑ 收敛稳/耗时↑；↓ 速度↑/易欠收敛
  move_thresh: 0.8          # 关键帧移动阈值m｜↑ 更稀疏/漂移风险↑；↓ 更密/耗时↑
  imu_noise:
    accelerometer: 0.005    # 加计噪声｜↑ 更保守/平滑；↓ 更敏感/抖动
    gyroscope: 0.005        # 陀螺噪声｜同上
    acc_bias: 0.0001        # 加计偏置噪声｜↑ 偏置不自信；↓ 偏置更可信
    gyro_bias: 5.0e-05      # 陀螺偏置噪声｜同上
  algorithm:
    imu_init_num: 500       # IMU初始化样本｜↑ 启动更稳/更慢；↓ 更快/不稳
    near_search_num: 8     # 最近邻数量｜↑ 稳定↑/耗时↑；↓ 速度↑/欠收敛（保持：配合更密地图更稳）
    ieskf_max_iter: 6       # 迭代次数｜↑ 精度↑/耗时↑；↓ 速度↑（轻微提高收敛余量）
    gravity_align: true     # 重力对齐
    esti_il: false           # 估计雷达-IMU外参
  point_cloud:
    lidar_cov_inv: 2000.0   # 点云置信度｜↑ 更信任点云/响应快；↓ 更依赖IMU
    lidar_cov_scale: 1.0    # 置信度缩放
    point_filter_num: 4     # 点云过滤级数｜↑ 速度↑/细节↓；↓ 细节↑/耗时↑
    converge_thresh: 0.0001 # 收敛阈值｜↑ 易早停/速度↑；↓ 更严格/精度↑
  buffer_management:
    max_imu_buffer_size: 8000   # IMU缓冲｜↑ 抗堵塞/掩盖问题；↓ 及时暴露问题（尾段乱序更稳）
    max_lidar_buffer_size: 100   # LiDAR缓冲｜↑ 抗抖动/内存↑；↓ 敏捷/丢帧风险↑
    enable_buffer_monitoring: true # 缓冲监控
  lidar_topic: /livox/lidar
  imu_topic: /livox/imu
visualization:
  rviz:
    auto_start: true        # 自动启动RViz｜↑ 便捷/资源↑；↓ 手动更轻量
    config_file: enhanced_fastlio2.rviz
    display:
      pointcloud: true      # ↑ 直观/显存↑；↓ 轻量
      trajectory: true      # ↑ 评估回环；↓ 轻量
      tf_frames: true       # ↑ 诊断方便；↓ 轻量
      imu_pose: true        # ↑ 检查IMU；↓ 轻量
      diagnostics: true     # ↑ 观测性能；↓ 轻量
rosbag:
  auto_record: false        # 自动录包｜↑ 取证/磁盘↑；↓ 手动控制
  topics:
  - /livox/lidar
  - /livox/imu
  - /slam/lio_odom
  - /slam/lio_path
  - /slam/body_cloud
  - /tf
  - /tf_static
  output_dir: data/rosbags
  compression_format: zstd  # zstd 压缩比↑/CPU↑；lz4 速度↑/压缩↓
  max_duration: 0           # 切包秒数｜0=不限；↑ 便于长期录制管理
monitoring:
  performance:
    enable_metrics: true    # 性能指标｜↑ 实时监控/CPU↑；↓ 轻量
    publish_frequency: 1.0  # Hz｜↑ 更实时/CPU↑；↓ 更轻量
  diagnostics:
    enable_diagnostics: true # 诊断检查｜↑ 敏感/CPU↑；↓ 轻量
    check_frequency: 2.0     # Hz｜↑ 更敏感/CPU↑；↓ 更轻量
  logging:
    level: INFO             # DEBUG/INFO/WARN/ERROR｜↑ 信息↑/刷屏；↓ 轻量
    verbose: false          # 详细日志｜↑ 细节/刷屏；↓ 安静
pgo:
  cloud_topic: /localizer/filtered_cloud   # PGO输入点云（回放预设）
  odom_topic: /slam/lio_odom
  map_frame: map
  local_frame: lidar
  key_pose_delta_deg: 10         # 关键帧角度阈值°｜↑ 更稀疏/速度↑；↓ 更密/耗时↑/回环稳
  key_pose_delta_trans: 0.3      # 关键帧位移阈值m｜↑ 更稀疏；↓ 更密
  loop_search_radius: 5.0        # 回环搜索半径m｜↑ 命中↑/误匹配风险↑/耗时↑；↓ 更保守
  loop_time_tresh: 10.0          # 回环时间阈值s｜↓ 更频繁/CPU↑；↑ 更少
  loop_score_tresh: 0.3          # 回环分数阈值｜↑ 更宽松(易通过)/误回环风险↑；↓ 更严格
  loop_submap_half_range: 5      # 子图半径｜↑ 匹配稳/耗时↑；↓ 更快
  submap_resolution: 0.1         # 子图分辨率m｜↑ 粗快；↓ 细慢
  min_loop_detect_duration: 2.0  # 检测间隔s｜↓ 更频繁；↑ 更少
hba:
  scan_resolution: 0.1       # 扫描分辨率m｜↑ 粗快；↓ 细慢
  window_size: 20            # 窗口大小｜↑ 精度↑/耗时↑；↓ 更快
  stride: 10                 # 步长｜↓ 更密/耗时↑；↑ 更稀疏
  voxel_size: 0.5            # 体素m｜↓ 细节↑/耗时↑；↑ 速度↑
  min_point_num: 10          # 最小点数｜↑ 稳定↑/耗时↑；↓ 速度↑/噪声↑
  max_layer: 3               # 最大层数｜↑ 表达力↑/耗时↑；↓ 更快
  plane_thresh: 0.01         # 平面阈值｜↑ 严格/更纯；↓ 宽松
  ba_max_iter: 10            # BA迭代｜↑ 精度↑/耗时↑；↓ 更快
  hba_iter: 5                # HBA迭代｜↑ 一致性↑/耗时↑；↓ 更快
  down_sample: 0.1           # 下采样m｜↑ 稀疏/速度↑；↓ 稠密/精度↑
localizer:
  cloud_topic: /slam/body_cloud
  odom_topic: /slam/lio_odom
  map_frame: map
  local_frame: lidar
  update_hz: 1.0             # 更新频率Hz｜↑ 响应↑/CPU↑；↓ 轻量
  rough_localization:
    scan_resolution: 0.25    # 粗配准扫描分辨率m｜↑ 粗快；↓ 细慢
    map_resolution: 0.25     # 粗地图分辨率m｜同上
    max_iteration: 5         # 粗配准迭代｜↑ 精度↑/耗时↑；↓ 更快
    score_thresh: 0.2        # 粗配准分数阈值｜↑ 严格；↓ 宽松
  refine_localization:
    scan_resolution: 0.1     # 精配准扫描分辨率m｜↑ 粗快；↓ 细慢
    map_resolution: 0.1      # 精地图分辨率m｜同上
    max_iteration: 10        # 精配准迭代｜↑ 精度↑/耗时↑；↓ 更快
    score_thresh: 0.1        # 精配准分数阈值｜↑ 严格；↓ 宽松
  dynamic_filter:
    enable: true             # 开启动态过滤｜↑ 地图更干净/CPU↑；↓ 轻量
    publish_stats: true      # 发布过滤统计｜↑ 调试方便/CPU↑；↓ 轻量
    motion_threshold: 0.1    # 运动阈值m｜↑ 保守(动态↓)；↓ 敏感(误检↑)
    history_size: 5          # 历史帧数｜↑ 稳定↑/延迟↑/耗时↑；↓ 实时↑
    stability_threshold: 0.8 # 稳定性判定0~1｜↑ 严格；↓ 宽松
    max_time_diff: 0.5       # 帧间最大时间差s｜↑ 历史利用↑；↓ 实时↑
    search_radius: 0.2       # 邻域半径m｜↑ 鲁棒↑/耗时↑；↓ 更快
    min_neighbors: 10        # 最小邻居数｜↑ 稳定↑；↓ 速度↑/噪声↑
    normal_consistency_thresh: 0.8 # 法向一致性阈值｜↑ 严格；↓ 宽松
    density_ratio_thresh: 0.5 # 密度比阈值｜↑ 严格；↓ 宽松
    downsample_ratio: 2       # 随机降采样倍数｜↑ 速度↑/细节↓；↓ 细节↑
    max_points_per_frame: 50000 # 单帧点数上限｜↑ 不丢点/耗时↑；↓ 更快
    voxel_size_base: 0.05     # 体素基础大小m｜↑ 更快/细节↓；↓ 更细/耗时↑
cooperation:
  enable: true
  drift_threshold: 0.5       # 漂移阈值m｜↓ 更敏感/优化更频；↑ 更保守
  time_threshold: 60.0       # 时间触发s｜↓ 更频繁；↑ 更少
  emergency_threshold: 2.0   # 紧急优化阈值m｜↓ 更容易触发；↑ 更保守
  auto_optimization: true
  multi_agent:
    max_agents: 4
    communication_freq: 5.0  # 通信频率Hz｜↑ 实时↑/带宽↑；↓ 轻量
validation:
  checks:
    network_connectivity: true
    calibration_consistency: true
    topic_availability: true
    parameter_ranges: true
  constraints:
    lidar_max_range:
      min: 1.0
      max: 100.0
    publish_freq:
      min: 1.0
      max: 50.0
    imu_init_num:
      min: 50
      max: 1000
