system:
  name: MID360_SLAM_System
  version: '2.0'
  description: 基于Livox MID360的实时SLAM建图系统
network:
  host:
    ip: 192.168.1.50
    interface: enp7s0
    gateway: 192.168.1.1
    netmask: 255.255.255.0
  lidar:
    ip: 192.168.1.3
    lidar_ports:
      cmd_data: 56100
      push_msg: 56200
      point_data: 56300
      imu_data: 56400
      log_data: 56500
    host_ports:
      cmd_data: 56101
      push_msg: 56201
      point_data: 56301
      imu_data: 56401
      log_data: 56501
calibration:
  lidar_to_imu:
    translation:
    - 0.011
    - 0.02329
    - -0.04412
    rotation:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  lidar_to_baselink:
    translation:
    - 0.0
    - 0.0
    - 0.0
    rotation_rpy:
    - 0.0
    - 0.0
    - 0.0
frames:
  world_frame: odom
  base_frame: base_link
  lidar_frame: livox_frame
topics:
  imu: /livox/imu
  lidar: /livox/lidar_filtered
  odometry: /slam/lio_odom
  path: /slam/lio_path
  body_cloud: /slam/body_cloud
  world_cloud: /slam/world_cloud
  loop_markers: /slam/loop_markers
  hba_map: /hba/map_points
  performance: /slam/performance_metrics
  diagnostics: /slam/diagnostics
livox_driver:
  xfer_format: 1
  multi_topic: 0
  data_src: 0
  publish_freq: 10.0
  output_data_type: 0
  frame_id: livox_frame
  cmdline_input_bd_code: livox0000000001
  lidar_config:
    pcl_data_type: 1
    pattern_mode: 0
fastlio2:
  print_time_cost: true
  lidar_filter_num: 1
  lidar_min_range: 0.3
  lidar_max_range: 30.0
  scan_resolution: 0.2
  map_resolution: 0.25
  cube_len: 100
  det_range: 30
  move_thresh: 0.6
  imu_noise:
    accelerometer: 0.005
    gyroscope: 0.005
    acc_bias: 0.0001
    gyro_bias: 5.0e-05
  algorithm:
    imu_init_num: 500
    near_search_num: 8
    ieskf_max_iter: 5
    gravity_align: true
    esti_il: false
  point_cloud:
    lidar_cov_inv: 2000.0
    lidar_cov_scale: 1.0
    point_filter_num: 4
    converge_thresh: 0.0001
  buffer_management:
    max_imu_buffer_size: 8000
    max_lidar_buffer_size: 1000
    enable_buffer_monitoring: true
  lidar_topic: /livox/lidar_filtered
  imu_topic: /livox/imu
visualization:
  rviz:
    auto_start: true
    config_file: enhanced_fastlio2.rviz
    display:
      pointcloud: true
      trajectory: true
      tf_frames: true
      imu_pose: true
      diagnostics: true
rosbag:
  auto_record: false
  topics:
  - /livox/lidar
  - /livox/imu
  - /slam/lio_odom
  - /slam/lio_path
  - /slam/body_cloud
  - /slam/world_cloud
  - /tf
  - /tf_static
  output_dir: data/rosbags
  compression_format: zstd
  max_duration: 0
monitoring:
  performance:
    enable_metrics: true
    publish_frequency: 1.0
  diagnostics:
    enable_diagnostics: true
    check_frequency: 2.0
  logging:
    level: INFO
    verbose: false
pgo:
  cloud_topic: /slam/body_cloud
  odom_topic: /slam/lio_odom
  map_frame: map
  local_frame: lidar
  log_level: INFO
  key_pose_delta_deg: 10
  key_pose_delta_trans: 0.3
  loop_search_radius: 6.0
  loop_time_tresh: 10.0
  loop_score_tresh: 0.35
  loop_submap_half_range: 5
  submap_resolution: 0.1
  min_loop_detect_duration: 2.0
  isam_relinearize_threshold: 0.05
  isam_relinearize_skip: 1
  loop_retry_max_attempts: 3
  loop_retry_interval: 5.0
  loop_retry_capacity: 32
  loop_retry_score_relax: 1.5
  loop_retry_inlier_relax: 0.7
hba:
  scan_resolution: 0.1
  window_size: 20
  stride: 10
  voxel_size: 0.5
  min_point_num: 10
  max_layer: 3
  plane_thresh: 0.01
  ba_max_iter: 10
  hba_iter: 5
  down_sample: 0.1
  min_pose_count: 5
localizer:
  cloud_topic: /slam/body_cloud
  odom_topic: /slam/lio_odom
  map_frame: map
  local_frame: lidar
  update_hz: 1.0
  rough_localization:
    scan_resolution: 0.25
    map_resolution: 0.25
    max_iteration: 5
    score_thresh: 0.2
  refine_localization:
    scan_resolution: 0.2
    map_resolution: 0.2
    max_iteration: 10
    score_thresh: 0.1
  dynamic_filter:
    enable: false
    publish_stats: true
    max_processing_hz: 20.0
    motion_threshold: 0.1
    history_size: 8
    stability_threshold: 0.75
    max_time_diff: 0.5
    search_radius: 0.2
    min_neighbors: 10
    normal_consistency_thresh: 0.8
    density_ratio_thresh: 0.5
    downsample_ratio: 2
    max_points_per_frame: 60000
    voxel_size_base: 0.03
cooperation:
  enable: true
  drift_threshold: 0.8
  time_threshold: 120.0
  emergency_threshold: 1.5
  emergency_failure_threshold: 3
  service_timeout_ms: 3000
  hba_maps_path: saved_maps/hba_workspace
  auto_optimization: true
  min_pose_delta: 0.05
  min_orientation_delta_deg: 1.0
  optimization_score_threshold: 0.4
  min_keyframes_for_hba: 5
  regular_optimization_min_interval: 30.0
  multi_agent:
    max_agents: 4
    communication_freq: 5.0
validation:
  checks:
    network_connectivity: true
    calibration_consistency: true
    topic_availability: true
    parameter_ranges: true
  constraints:
    lidar_max_range:
      min: 1.0
      max: 100.0
    publish_freq:
      min: 1.0
      max: 50.0
    imu_init_num:
      min: 50
      max: 1000
