# FAST-LIO2配置文件
# 由配置生成器自动生成，请勿手动修改
# 生成时间: 2025-09-23 22:47:35
# 主配置文件: /home/tianyu/codes/Mid360map/config/master_config.yaml

body_frame: base_link
cube_len: 200
det_range: 50
enable_buffer_monitoring: true
esti_il: true
gravity_align: true
ieskf_max_iter: 4
imu_init_num: 200
imu_topic: /livox/imu
lidar_cov_inv: 2000.0
lidar_filter_num: 3
lidar_max_range: 25.0
lidar_min_range: 0.5
lidar_topic: /livox/lidar
map_resolution: 0.1
max_imu_buffer_size: 1000
max_lidar_buffer_size: 50
move_thresh: 1.0
na: 0.005
nba: 0.0001
nbg: 5.0e-05
near_search_num: 15
ng: 0.005
print_time_cost: true
r_il:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
scan_resolution: 0.1
t_il:
- 0.011
- 0.02329
- -0.04412
world_frame: odom
