# 点云过滤桥接参数文件
# 由配置生成器自动生成，请勿手动修改
# 生成时间: 2025-09-27 11:08:49
# 主配置文件: /home/tianyu/codes/Mid360map/config/master_config.yaml
# 使用说明:
#  - input_topic 为驱动原始话题（一般为 /livox/lidar）
#  - output_topic 与 fastlio2 订阅保持一致（一般为 /livox/lidar_filtered）
#  - dynamic_filter.* 为性能/精度的关键参数，调高更稳更慢，调低更快更敏感

point_cloud_filter_bridge:
  ros__parameters:
    input_topic: /livox/lidar
    output_topic: /livox/lidar_filtered
    debug_topic: /point_cloud_filter/debug_cloud
    stats_topic: /point_cloud_filter/filter_stats
    debug_enabled: false
    publish_stats: true
    max_processing_hz: 20.0
    dynamic_filter:
      debug_enabled: false
      motion_threshold: 0.1
      history_size: 5
      stability_threshold: 0.8
      max_time_diff: 0.5
      search_radius: 0.2
      min_neighbors: 10
      normal_consistency_thresh: 0.8
      density_ratio_thresh: 0.5
      downsample_ratio: 2
      max_points_per_frame: 50000
      voxel_size_base: 0.01
