# ====================================================================
# 地图精细化工具优化配置文件 - 针对无建筑物区域噪点问题优化
# ====================================================================
# 本配置专门解决地图精细化后在无建筑物区域产生噪点的问题
# 主要优化：关闭空洞填补，降低目标密度，优化去噪参数
# ====================================================================

# ====================================================================
# 1. 法向量ICP增强配准算法配置
# ====================================================================
normal_icp:
  max_iterations: 50
  convergence_threshold: 1e-6
  normal_search_radius: 0.1
  normal_weight: 0.7
  distance_weight: 0.3
  angle_threshold: 30.0

# ====================================================================
# 2. 平面结构保护算法配置
# ====================================================================
plane_preserver:
  ransac_distance_threshold: 0.02
  ransac_max_iterations: 1000
  min_plane_points: 100
  parallel_threshold: 5.0
  perpendicular_threshold: 85.0

# ====================================================================
# 3. 边缘特征强化算法配置
# ====================================================================
edge_enhancer:
  curvature_threshold: 0.1
  edge_search_radius: 0.05
  edge_weight_multiplier: 2.0
  line_feature_min_points: 20

# ====================================================================
# 4. 几何约束优化算法配置
# ====================================================================
geometry_optimizer:
  enable_parallel_constraint: true
  enable_perpendicular_constraint: true
  enable_distance_constraint: true
  enable_angle_constraint: true
  constraint_weight: 0.5

# ====================================================================
# 5. 点云去噪算法配置 - 针对空旷区域优化
# ====================================================================
noise_reduction:
  # 统计异常值去除 - 更严格的参数
  statistical_outlier:
    # 增加邻近点数量，提高判断准确性
    mean_k: 30
    # 降低标准差阈值，更严格去除异常值
    std_dev_mul_thresh: 1.5

  # 半径异常值去除 - 针对稀疏噪声优化
  radius_outlier:
    # 增大搜索半径，更好识别孤立点
    radius: 0.4
    # 增加最小邻近点数要求
    min_neighbors: 5

  # 密度过滤 - 关键优化：严格过滤低密度区域
  density_filter:
    # 显著提高最小密度要求，严格过滤稀疏区域
    # 这将有效移除无建筑物区域的稀疏噪声
    min_density: 25

  # 自适应噪声去除配置 - 强化空旷区域噪声识别
  adaptive_denoising:
    # 使用更保守的模式，避免过度处理
    mode: "conservative"

    # 调整特征权重，更重视密度特征
    feature_weights:
      # 降低曲率权重，避免误判平坦区域
      curvature: 0.15
      # 保持法向量变化权重
      normal_variation: 0.25
      # 增加密度权重，强化对稀疏区域的识别
      density: 0.35

    # 使用更保守的阈值方法
    threshold_method: "percentile"
    # 提高百分位数，更保守的去噪
    noise_percentile: 90

# ====================================================================
# 6. 表面重建算法配置 - 禁用以避免人工表面
# ====================================================================
surface_reconstruction:
  # 禁用表面重建，避免在空旷区域创建人工表面
  method: "disabled"
  poisson_depth: 9
  poisson_width: 0
  poisson_scale: 1.1

# ====================================================================
# 7. 细节保护算法配置 - 保守设置
# ====================================================================
detail_preservation:
  # 减少多尺度层级，避免过度处理
  multi_scale_levels: 2
  # 降低边缘敏感度，避免在平坦区域误检边缘
  edge_sensitivity: 0.6
  # 禁用纹理增强，避免增加噪声
  texture_enhancement: false

# ====================================================================
# 8. 密度均匀化算法配置 - 关键优化区域
# ====================================================================
density_uniformization:
  # 显著降低目标密度，避免在空旷区域强制填充
  # 从100降低到30，减少70%的人工点云生成
  target_density: 30

  # 关闭自适应采样，避免在稀疏区域插值
  adaptive_sampling: false

  # 关闭空洞填补 - 这是最关键的修改
  # 保持原始地图的空旷区域，不强制填充
  hole_filling: false

  # 使用最近邻插值，避免创建不存在的中间点
  interpolation_method: "nearest"

# ====================================================================
# 9. 输出控制配置
# ====================================================================
output:
  save_intermediate_results: true
  quality_report: true
  visualization: true

# ====================================================================
# 10. 性能优化配置
# ====================================================================
performance:
  num_threads: 16
  memory_limit_gb: 16
  progress_display: true
  progress_bar:
    use_tqdm: true
    refresh_rate: 0.1
    show_nested: true
  optimization_strategy: "auto"

# ====================================================================
# 新增：空旷区域检测配置
# ====================================================================
# 专门针对无建筑物区域的检测和处理配置
open_space_detection:
  # 启用空旷区域检测
  enabled: true

  # 空旷区域判断的密度阈值 (点/立方米)
  # 低于此密度的区域将被视为空旷区域，不进行密度填充
  density_threshold: 5

  # 空旷区域检测的搜索半径 (米)
  search_radius: 1.0

  # 空旷区域的最小体积 (立方米)
  # 小于此体积的空旷区域可能是噪声，仍进行处理
  min_volume: 2.0

  # 是否在空旷区域完全跳过处理
  skip_processing: true

# ====================================================================
# 针对性处理管道配置
# ====================================================================
# 定义专门的处理管道，跳过容易产生噪声的步骤
processing_pipeline:
  # 自定义管道：只进行去噪和结构保护，跳过密度均匀化
  custom_pipeline: ["denoise", "structure", "edges"]

  # 是否跳过密度均匀化步骤
  skip_density_uniformization: true

  # 是否跳过表面重建步骤
  skip_surface_reconstruction: true
