'# MID360 启动配置文件': null
'# 由配置生成器自动生成，请勿手动修改': null
debug:
  log_level: INFO
  performance_monitor: true
  verbose: false
lidar:
  extrinsic:
    pitch: 0.0
    roll: 0.0
    x: 0.0
    y: 0.0
    yaw: 0.0
    z: 0.0
  frame_id: livox_frame
  pcl_data_type: 1
  publish_freq: 10.0
network:
  gateway: 192.168.1.1
  host_ip: 192.168.1.50
  interface: enp7s0
  lidar_ip: 192.168.1.3
  netmask: 255.255.255.0
  ports:
    cmd_data: 56100
    imu_data: 56400
    log_data: 56500
    point_data: 56300
    push_msg: 56200
rosbag:
  auto_record: false
  compression_format: zstd
  max_duration: 0
  output_dir: data/rosbags
  topics:
  - /livox/lidar
  - /livox/imu
  - /fastlio2/lio_odom
  - /fastlio2/lio_path
  - /fastlio2/body_cloud
  - /tf
  - /tf_static
rviz:
  auto_start: true
  config_file: enhanced_fastlio2.rviz
  display:
    diagnostics: true
    imu_pose: true
    pointcloud: true
    tf_frames: true
    trajectory: true
